### ISSUE TITLE
View location of the ip address (For admins) to trace down griefers easier

### ISSUE THREAD

**Issue by ARYDESTROYER** [LinMindustry/Mindustry#17]
When we do "/info" with uid or IP a full screenshot display like it does on other servers and should tell us the location of each IP for better tracing and investigating griefers, if we get their vpns name, we could block all those proxies. For the country name you can use an Api GET query from various sites that offer it for free. Thank You for your hard work.

**Comment by SylerFire** [comment]
on /show put the trace up the top center of the screen.
![image](https://user-images.githubusercontent.com/68886426/89263903-69a28e00-d675-11ea-9bc3-9d20d52ec82e.png)
